In [1]:
import kinkit as kin
import numpy as np

In [2]:
t1 = np.pi/3
t2 = -np.pi/4
t3 = -np.pi/6

# DCM from Euler Angle Sequence (Forward Mapping)

This depicts finding the DCM for a 123 sequence (R1, R2, R3) = (t1, t2, t3).

In [3]:
DCM123 = kin.EAtoDCM(123, t1, t2, t3)
DCM123

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

In [4]:
np.round(np.matmul(DCM123,DCM123.transpose()))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

We have verified the DCM is orthogonal

# Euler Angle from DCM (Inverse Mapping)

Here, we take the DCM of the 123 Euler Angle Seqence and inverse map to find the 323 sequence for that rotation.

In [21]:
EA323 = kin.DCMtoEA(323, DCM123)
EA323

array([-2.42786827,  1.2094292 ,  1.43479424])

In [6]:
DCM323 = kin.EAtoDCM(323, EA323[0], EA323[1], EA323[2])
DCM323

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

We have verified that the original DCM is returned through forward mapping.

# Other Forward Mapping Functions

In [8]:
kin.DCMtoPRP(DCM123)

(1.5244035316163185, array([ 0.77040348, -0.29045266, -0.5675524 ]))

In [10]:
kin.DCMtoEP(DCM123)

array([ 0.5319757 , -0.20056212, -0.39190384,  0.72331741])

In [13]:
kin.DCMtoCRP(DCM123)

array([ 0.73546646, -0.27728093, -0.54181447])

In [14]:
kin.DCMtoMRP(DCM123)

array([ 0.30869281, -0.11638142, -0.22741245])

In [11]:
np.linalg.norm(kin.DCMtoEP(DCM123))

0.9999999999999999

Unit norm constraint met for Euler Parameter

# Inverse Mapping Functions

We can pass the DCM into the forward mapping function (for instance, DCM -> CRP). We then pass it back through an inverse mapping (CRP -> DCM). The result must be the original DCM.

In [15]:
kin.PRPtoDCM(kin.DCMtoPRP(DCM123))

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

In [16]:
kin.EPtoDCM(kin.DCMtoEP(DCM123))

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

In [18]:
kin.CRPtoDCM(kin.DCMtoCRP(DCM123))

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

In [19]:
kin.MRPtoDCM(kin.DCMtoMRP(DCM123))

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])