In [1]:
import kinkit as kin
import numpy as np

In [2]:
t1 = np.pi/3
t2 = -np.pi/4
t3 = -np.pi/6

In [3]:
DCM123 = kin.EAtoDCM(123, t1, t2, t3)
DCM123

array([[ 0.61237244, -0.78033009, -0.12682648],
       [ 0.35355339,  0.12682648,  0.9267767 ],
       [-0.70710678, -0.61237244,  0.35355339]])

In [4]:
np.round(np.matmul(DCM123,DCM123.transpose()))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [5]:
EA323 = kin.DCMtoEA(323, DCM123)
EA323*(180/np.pi)

array([  82.2076543 ,   69.29518895, -139.10660535])

In [6]:
DCM323 = kin.EAtoDCM(323, EA323[0], EA323[1], EA323[2])
DCM323

array([[ 0.61237244, -0.35355339,  0.70710678],
       [ 0.78033009,  0.12682648, -0.61237244],
       [ 0.12682648,  0.9267767 ,  0.35355339]])